# Generated by Django 4.2 on 2025-02-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('1', '高'), ('2', '中'), ('3', '低')], max_length=1)),
                ('deadline', models.DateTimeField()),
                ('text', models.TextField()),
            ],
        ),
    ]
