# Generated by Django 4.2 on 2025-02-10 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='author',
        ),
    ]
